language: node_js
before_script:
    - npm run keys
    - npm run build
node_js:
    - '6.11.5'
script: cd server && npm install && npm run deploy
deploy:
    provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    keep-history: true
    on:
        branch: master
